zcash/orchard

book/src/design/nullifiers.md
While reviewing my local changes for #10, @daira and I broke the previous design 😄
I'm still working on writing up the nullifier rationale in #10 (a large part of which now needs rewriting :sigh:). In the meantime, this PR:
- Updates the Faerie Resistance assumptions for the alternatives.
- Switches the book to specify the new nullifier design (selected from the alternatives).
- Documents the main reason for rejecting the other alternatives.
=> book: New nullifier design

CHANGELOG.md
Adds a base structure to the changelog. Once the first release has been cut, we can start tracking changes using the [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) format. For an example of this format in action, see https://github.com/str4d/rage/blob/master/age/CHANGELOG.md
=> Initialize the changelog

Cargo.toml, src/primitives.rs, src/primitives/sinsemilla.rs
Test vectors will be added in a subsequent PR.
=> Implement Sinsemilla primitives

Cargo.toml, src/address.rs, src/constants.rs, src/keys.rs, src/lib.rs, src/primitives/redpallas.rs, src/primitives/sinsemilla.rs, src/spec.rs
=> Orchard key components

Cargo.toml, benches/small.rs, src/lib.rs
This will silence the benchmark CI failure, as we will finally have some benchmarks 😄
Closes #39.
=> Add small key derivation benchmarks

.github/workflows/ci.yml, .github/workflows/lints-nightly.yml, .github/workflows/lints-stable.yml
We move Clippy lints into separate workflows that only run either directly on branches, or on trial-merges of PRs, to deduplicate the lint annotations. We will still see stable lints duplicated in nightly, but that's fine.
=> CI: Reduce noise of clippy lints

book/src/design/commitments.md, src/address.rs, src/keys.rs, src/note.rs, src/note/commitment.rs, src/note/nullifier.rs, src/spec.rs
The implementation was previously (supposed to be) implementing version 2021.1.20 of the protocol spec.
Closes #79.
=> Update implementation to match protocol spec version 2021.2.0

Cargo.toml, src/builder.rs, src/bundle.rs, src/keys.rs, src/primitives/redpallas.rs
Upstream `redjubjub` (on which our `reddsa` dependency is based) has migrated to `rand 0.8`.
=> Remove rand 0.7 usage

src/keys.rs, src/note.rs, src/spec.rs, src/spec/prf_expand.rs
`prf_expand{_vec}` have been replaced by the `PrfExpand` enum, which has `PrfExpand::{expand, with_ad, with_ad_slices}` methods for use within each domain as necessary.
=> Define explicit domains for PRF^expand

src/constants.rs, src/constants/commit_ivk_r.rs, src/constants/load.rs, src/constants/note_commit_r.rs, src/constants/nullifier_k.rs, src/constants/spend_auth_g.rs, src/constants/value_commit_r.rs, src/constants/value_commit_v.rs
This makes it easier to load constants into the ECC chip.
=> Refactor `constants` to add `constants::load`

src/builder.rs, src/keys.rs, src/primitives/redpallas.rs
This was missed from zcash/orchard#49, but could not have caused a consensus failure, loss-of-funds, or privacy violation because `alpha` _was_ being sampled and used to derive `rk`, meaning that the signatures would fail to validate.
Closes zcash/orchard#102.
=> builder: Store alpha and use it to derive rsk for signing spends

src/constants.rs, src/constants/commit_ivk_r.rs, src/constants/load.rs, src/constants/note_commit_r.rs, src/constants/nullifier_k.rs, src/constants/spend_auth_g.rs, src/constants/value_commit_r.rs, src/constants/value_commit_v.rs
The Orchard fixed bases are Pallas curve points and are not generic over other curves.
=> `constants::load.rs`: Use concrete `pallas::Affine` type for generators

src/circuit/gadget/utilities.rs, src/circuit/gadget/utilities/lookup_range_check.rs, src/primitives/sinsemilla.rs, src/primitives/sinsemilla/constants.rs, src/spec.rs
This decomposes a field element into K-bit words and constrains each word's range by looking it up in a K-bit lookup table.
The field element is broken down using a running sum. All interstitial values of the running sum are returned.
=> utilities::lookup_range_check: Add LookupRangeCheck helper

Cargo.toml
While these two are in flux, it's hard to keep these revisions consistent
(e.g. https://github.com/zcash/zcash/pull/5217 currently depends on two
different versions of zcash_note_encryption). Using patches allows the
downstream users (i.e. zcashd) to define its own set of patches, and keep
everything in sync. This works fine now because we aren't actively making
changes to the public APIs, only additions.
=> Use patches for halo2 and zcash_note_encryption dependencies

src/builder.rs, src/bundle.rs, src/circuit.rs, src/tree.rs
This matches what we store in `MerklePath`, and better enforces the required type.
=> Store anchors as pallas::Base instead of [u8; 32]

src/builder.rs, src/note/commitment.rs, src/note_encryption.rs
This makes `orchard` clippy-clean on stable, beta, and nightly.
=> Fix clippy lints

src/circuit/gadget/ecc/chip.rs, src/circuit/gadget/ecc/chip/mul/overflow.rs
Range-check the low 130 bits rather than the low 127 bits.
=> Simplify the canonicity check for variable-base scalar multiplication

src/circuit/gadget/ecc/chip/mul_fixed.rs, src/constants/load.rs
Together these decrease proving time in the Action circuit by 60%.
=> Simple proving optimizations in `ecc/chip/mul_fixed.rs`

src/circuit/gadget/poseidon.rs, src/circuit/gadget/poseidon/pow5t3.rs, src/keys.rs, src/note_encryption.rs, src/primitives/poseidon.rs, src/spec.rs
One .clone() removal; all of the other changes are removing needless borrows that are immediately
dereferenced: https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
=> Make this crate clippy clean for warnings on nightly

src/circuit/gadget.rs, src/circuit/gadget/ecc/chip.rs, src/circuit/gadget/sinsemilla.rs, src/circuit/gadget/sinsemilla/chip.rs, src/circuit/gadget/sinsemilla/chip/generator_table.rs, src/circuit/gadget/sinsemilla/chip/hash_to_point.rs, src/circuit/gadget/sinsemilla/message.rs, src/primitives/sinsemilla.rs, src/primitives/sinsemilla/constants.rs
Part of #96. This PR only covers `SinsemillaHash`, not `SinsemillaCommit`.
The `SinsemillaCommit` functionality is in https://github.com/zcash/orchard/pull/118.
=> Sinsemilla chip with HashDomain

src/bundle.rs, src/circuit.rs
This will be used by `zcashd` as part of tracking the memory usage of transactions.
=> Add `Bundle<Authorized, _>::dynamic_usage` method

Cargo.toml, src/bundle.rs
We can now correctly measure the heap-allocated memory used by a bundle.
=> nonempty 0.7

src/circuit/gadget/utilities.rs, src/circuit/gadget/utilities/cond_swap.rs, src/circuit/gadget/utilities/lookup_range_check.rs
This PR introduces a range check for field elements <= `K` bits, using two lookups in a `K`-bit table.
This also introduces a `strict` mode for the full-length lookup (for field elements greater than `K` bits) to constrain the final running sum to 0.
=> Add short range check to `lookup_range_check` util

src/circuit/gadget/sinsemilla.rs, src/circuit/gadget/sinsemilla/chip.rs, src/circuit/gadget/sinsemilla/message.rs
Based on #132.
Inputs to Sinsemilla are commonly decomposed into subpieces and packed into field elements. These subpieces have to be range-checked. This PR includes a `LookupRangeCheckConfig` for each Sinsemilla advice column, to enable subpieces to be looked up in any advice column.
This PR also moves certain APIs from the instruction level to the gadget level.
=> Introduce `LookupRangeCheckConfig`s for each Sinsemilla advice column

src/circuit/gadget/sinsemilla.rs, src/circuit/gadget/sinsemilla/chip.rs, src/circuit/gadget/sinsemilla/merkle.rs, src/circuit/gadget/sinsemilla/merkle/chip.rs, src/circuit/gadget/utilities.rs, src/primitives/sinsemilla.rs, src/spec.rs
=> Merkle hash chip

Cargo.toml, src/circuit/gadget/ecc.rs, src/circuit/gadget/ecc/chip.rs, src/circuit/gadget/ecc/chip/add.rs, src/circuit/gadget/ecc/chip/add_incomplete.rs, src/circuit/gadget/ecc/chip/mul.rs, src/circuit/gadget/ecc/chip/mul/complete.rs, src/circuit/gadget/ecc/chip/mul/incomplete.rs, src/circuit/gadget/ecc/chip/mul/overflow.rs, src/circuit/gadget/ecc/chip/mul_fixed.rs, src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs, src/circuit/gadget/ecc/chip/mul_fixed/full_width.rs, src/circuit/gadget/ecc/chip/mul_fixed/short.rs, src/circuit/gadget/ecc/chip/witness_scalar_fixed.rs, src/circuit/gadget/ecc/chip/witness_scalar_fixed/full_width.rs, src/circuit/gadget/ecc/chip/witness_scalar_fixed/short.rs, src/circuit/gadget/sinsemilla.rs, src/circuit/gadget/utilities.rs, src/constants.rs, src/constants/load.rs, src/spec.rs
=> [ECC chip] Fixed- and variable-base scalar multiplication

Cargo.toml, src/circuit.rs, src/circuit/gadget/ecc.rs, src/circuit/gadget/poseidon/pow5t3.rs, src/circuit/gadget/sinsemilla.rs, src/circuit/gadget/sinsemilla/merkle.rs, src/circuit/gadget/utilities.rs, src/circuit/gadget/utilities/cond_swap.rs, src/circuit/gadget/utilities/enable_flag.rs, src/circuit/gadget/utilities/lookup_range_check.rs, src/circuit/gadget/utilities/plonk.rs
- The `Circuit` trait now has a `FloorPlanner` associated type.
- `circuit_layout` has been replaced by `CircuitLayout`.
=> Migrate to latest `halo2::plonk::Circuit` API

Cargo.toml, src/circuit.rs, src/circuit/gadget/ecc.rs, src/circuit/gadget/ecc/chip.rs, src/circuit/gadget/ecc/chip/add.rs, src/circuit/gadget/ecc/chip/add_incomplete.rs, src/circuit/gadget/ecc/chip/mul.rs, src/circuit/gadget/ecc/chip/mul/complete.rs, src/circuit/gadget/ecc/chip/mul/incomplete.rs, src/circuit/gadget/ecc/chip/mul/overflow.rs, src/circuit/gadget/ecc/chip/mul_fixed.rs, src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs, src/circuit/gadget/ecc/chip/mul_fixed/short.rs, src/circuit/gadget/poseidon/pow5t3.rs, src/circuit/gadget/sinsemilla.rs, src/circuit/gadget/sinsemilla/chip.rs, src/circuit/gadget/sinsemilla/chip/hash_to_point.rs, src/circuit/gadget/sinsemilla/merkle.rs, src/circuit/gadget/sinsemilla/merkle/chip.rs, src/circuit/gadget/utilities.rs, src/circuit/gadget/utilities/cond_swap.rs, src/circuit/gadget/utilities/decompose_running_sum.rs, src/circuit/gadget/utilities/enable_flag.rs, src/circuit/gadget/utilities/lookup_range_check.rs, src/circuit/gadget/utilities/plonk.rs
- `halo2::plonk::{create_proof, verify_proof}` now take instance columns
as slices of values.
- `halo2::plonk::Permutation` has been replaced by a global permutation,
to which columns can be added with `ConstraintSystem::enable_equality`.
- The introduction of blinding rows means that various tests now require
larger circuit parameters.
- `VerifyFailure::Constraint` is now `VerifyFailure::ConstraintNotSatisfied`.
=> Migrate to latest `halo2` API

src/constants.rs, src/constants/util.rs, src/note/commitment.rs, src/primitives/sinsemilla.rs, src/spec.rs
Minor fixes involving constants:
- document that `find_zs_and_us()` is not meant to be used anywhere;
- use `F::zero()` instead of `F::default()` in `constants/util.rs`;
- use personalisations from `constants` in `spec.rs`.
In `primitives/sinsemilla.rs`: document that `hash()` panics if the message is longer than `K * C`.
=> Partial fixes from NCC draft report

book/src/design/circuit/gadgets/ecc/var-base-scalar-mul.md, book/src/design/circuit/gadgets/sinsemilla.md
To make use of the binary selector optimisations in https://github.com/zcash/halo2/pull/347, we decompose non-binary selectors into binary selectors.
These book changes will be implemented in #101.
=> [Book] Undo selector optimisations

book/src/design/circuit/gadgets/sinsemilla.md
Since q_S1, q_S2, q_S3 are not simple selectors, they cannot be
automatically combined. We manually combine them here.
=> [book] Recombine Sinsemilla q_S1, q_S2, q_S3 selectors.

book/src/design/circuit/gadgets/decomposition.md
This is a small follow-up to #162.
=> [book] decomposition.md: avoid introducing `m` when we already have `range`

Cargo.toml, benches/circuit.rs, src/builder.rs, src/bundle.rs
This benchmarks the prover and verifier for `Bundle`s produced by the `Builder` with between 1 and 3 outputs; in particular this means the `Bundle`s will follow any defaults set by the `Builder` (currently that it has a minimum of two `Action`s).
In order to enable benchmarking the prover with minimal changes to the public API, `Builder::build` has been altered to not create the proof. The caller can now choose when to perform this, at any point after then but before signature finalization.
The PR also fixes a bug in the `Builder`'s `Circuit` initialization (from #101).
=> Add Action circuit benchmarks, fix Builder bug

src/bundle.rs, src/bundle/commitments.rs
This extracts the ZIP-244 hashing logic from librustzcash. The corresponding librustzcash PR is https://github.com/zcash/librustzcash/pull/411
=> Implement ZIP-244 txid and authorizing commitments.

Cargo.toml, src/spec.rs
Improves the base-line cost of trial decryption by over 40%.
=> Use w-NAF in `ka_orchard`

src/note/commitment.rs
=> ExtractedNoteCommitment::from_bytes: Document cmx canonicity. 

src/circuit/gadget/poseidon.rs, src/circuit/gadget/poseidon/pow5t3.rs, src/primitives/poseidon.rs
The methods in the `Domain` trait are not generic over `Spec`.
=> poseidon::Domain: Remove Spec trait bound.

src/circuit/gadget/ecc/chip/add_incomplete.rs, src/circuit/gadget/ecc/chip/mul.rs, src/circuit/gadget/ecc/chip/mul/complete.rs, src/circuit/gadget/ecc/chip/mul/overflow.rs, src/circuit/gadget/ecc/chip/witness_point.rs, src/circuit/gadget/poseidon/pow5t3.rs, src/circuit/gadget/sinsemilla/commit_ivk.rs, src/circuit/gadget/sinsemilla/note_commit.rs
Per https://github.com/zcash/orchard/pull/169#issuecomment-889423971:
- Base proof size increases by 64 bytes.
- Marginal (per-action) proof size decreases by 160 bytes.
Part of zcash/orchard#125.
Part of zcash/orchard#168.
=> Circuit constraint refinements to reduce proof size

COPYING, Cargo.toml, README.md
Also bumps the `pasta_curves` and `halo2` dependencies for compatibility.
=> Add license exceptions for ECC and ZF projects

Cargo.toml
This is equivalent to the git revision we were previously patching.
=> Switch to halo2 0.1.0-beta.1

src/circuit.rs
When using `orchard` to validate Halo2 proofs, the only public option right now is to use `orchard::Bundle::verify_proof()`, which requires us to construct a whole `Bundle` instance, including encrypted ciphertext, ephemeral keys, and other data we don't need to verify the proof. 
Adding a public constructor for `orchard::circuit::Instance` will allow us to call `orchard::circuit::Proof::verify()` directly with less unnecessary data shuffling.
=> Add `orchard::circuit::Instance::from_parts()`

src/keys.rs
`slice::copy_from_slice` panics if the source and destination slices are not the same length.
Closes zcash/orchard#228.
=> Fix `IncomingViewingKey::to_bytes`

Cargo.toml, benches/poseidon.rs, benches/primitives.rs, src/circuit.rs, src/circuit/gadget.rs, src/circuit/gadget/poseidon.rs, src/circuit/gadget/poseidon/pow5.rs, src/circuit/gadget/utilities.rs, src/primitives/poseidon.rs, src/primitives/poseidon/p128pow5t3.rs, src/spec.rs
Run `cargo bench --bench poseidon`.
Closes #215.
Based on #220.
=> Benchmark Poseidon gadget for rates {2, 8, 11}

src/keys.rs, src/zip32.rs
=> Replace `PartialEq, PartialOrd` with `ConstantTimeEq` on `{Extended}SpendingKey`

src/circuit.rs
This is to ensure that if any future circuit changes are made, their effect on the proof size (if any) will be noticed.
=> circuit: Pin the proof size

src/circuit.rs, src/circuit/gadget/ecc/chip.rs, src/circuit/gadget/ecc/chip/add.rs, src/circuit/gadget/ecc/chip/add_incomplete.rs, src/circuit/gadget/ecc/chip/mul.rs, src/circuit/gadget/ecc/chip/mul/complete.rs, src/circuit/gadget/ecc/chip/mul/incomplete.rs, src/circuit/gadget/ecc/chip/mul/overflow.rs, src/circuit/gadget/ecc/chip/mul_fixed.rs, src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs, src/circuit/gadget/ecc/chip/mul_fixed/full_width.rs, src/circuit/gadget/ecc/chip/mul_fixed/short.rs, src/circuit/gadget/ecc/chip/witness_point.rs, src/circuit/gadget/sinsemilla.rs, src/circuit/gadget/sinsemilla/commit_ivk.rs, src/circuit/gadget/sinsemilla/merkle.rs, src/circuit/gadget/sinsemilla/note_commit.rs, src/circuit/gadget/utilities/decompose_running_sum.rs, src/circuit/gadget/utilities/lookup_range_check.rs, src/circuit_description
Closes #246. Based on #247. 
Review recommendation: commit-by-commit, with whitespace changes hidden.
This PR introduces a `configure()` method for each sub-config, refactoring away from the `impl From<EccConfig>` pattern. This allows each sub-config to enable equalities for the columns it needs.
This PR changes the order in which columns and gates are created; however, it DOES NOT change the number of columns.
=> circuit: Refactor `EccConfig` away from `impl From<EccConfig>`.

CHANGELOG.md, Cargo.toml, benches/circuit.rs, benches/note_decryption.rs, benches/poseidon.rs, src/builder.rs, src/circuit.rs, src/circuit/gadget/ecc/chip/add.rs, src/circuit/gadget/ecc/chip/add_incomplete.rs, src/circuit/gadget/ecc/chip/mul/complete.rs, src/circuit/gadget/ecc/chip/mul/incomplete.rs, src/circuit/gadget/ecc/chip/mul/overflow.rs, src/circuit/gadget/ecc/chip/mul_fixed.rs, src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs, src/circuit/gadget/ecc/chip/mul_fixed/short.rs, src/circuit/gadget/poseidon/pow5.rs, src/circuit/gadget/sinsemilla/chip.rs, src/circuit/gadget/sinsemilla/commit_ivk.rs, src/circuit/gadget/sinsemilla/note_commit.rs, src/circuit/gadget/utilities.rs, src/circuit/gadget/utilities/cond_swap.rs, src/circuit/gadget/utilities/decompose_running_sum.rs, src/circuit/gadget/utilities/lookup_range_check.rs
Updating to reflect API changes in `halo2`:
- we no longer need to call `.into()` on arguments to `enable_equality()`, as of https://github.com/zcash/halo2/pull/416;
- the `create_proof()` API now expects an `rng` argument, as of https://github.com/zcash/halo2/pull/444;
- `MockProver::FailureLocation` was introduced in https://github.com/zcash/halo2/pull/433.
=> Update `halo2` revision

src/circuit/gadget/ecc/chip/mul.rs, src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs, src/circuit/gadget/ecc/chip/mul_fixed/full_width.rs, src/circuit/gadget/poseidon/pow5.rs, src/circuit/gadget/sinsemilla.rs, src/circuit/gadget/sinsemilla/commit_ivk.rs, src/circuit/gadget/sinsemilla/merkle.rs, src/circuit/gadget/sinsemilla/note_commit.rs, src/circuit/gadget/utilities.rs, src/circuit/gadget/utilities/cond_swap.rs, src/circuit/gadget/utilities/decompose_running_sum.rs
These were missed in zcash/orchard#254.
=> Migrate tests from `FieldExt::rand` to `Field::random`

src/builder.rs, src/keys.rs
Callers cannot assume that any specific output corresponds to a specific
Orchard recipient, and must trial-decrypt all outputs to find the ones
belonging to them. This is consistent with higher-layer semantics like
having Unified Addresses as recipients (where the mapping from recipient
to a specific output would become much more complex).
Closes zcash/orchard#203.
Co-authored-by: Daira Hopwood <daira@jacaranda.org>
=> Shuffle spends and recipients before pairing them into Actions

src/builder.rs, src/circuit.rs, src/keys.rs, src/note/commitment.rs, src/primitives/redpallas.rs
This enables `InProgress<Unproven, Unauthorized>: Clone`, which allows
the bundle returned by `Builder::build` to be cloned. In pure-Rust
wallets this should not be necessary, but it is required for `zcashd`
due to FFI-crossing.
=> Add `Clone` impls to various structs

src/bundle.rs, src/bundle/commitments.rs, src/primitives/redpallas.rs, src/tree.rs, tests/builder.rs
This also makes some changes to the public API that are necessary to enable an `orchard` user to perform this workflow themselves.
=> Functional test for building and verifying bundles

src/keys.rs, src/spec/prf_expand.rs
This is identical to the changes introduced in zcash/orchard#270, except that the output is non-optional (since the derivation is non-fallible). This PR is needed because that PR was not based on non-circuit changes, but we need it before bringing the circuit changes into `zcashd`.
=> Add `FullViewingKey::derive_internal`

src/builder.rs, src/bundle.rs
All relevant types have `Debug` impls, but some of the trait and method impls were lacking `Debug` bounds on their generic types. This prevented `Debug` impls being used on the overall partially-constructed `Bundle` types.
=> Add missing `Debug` trait bounds for `Builder` components

CHANGELOG.md, src/builder.rs, src/bundle.rs
=> Rename `Bundle::{try_}authorize` to `Bundle::{try_}map_authorization`

src/note_encryption.rs
Also reorders the fields to match the ZIP 244 order.
Closes zcash/orchard#243.
=> Add nullifier field to `CompactAction`

Cargo.toml
https://github.com/ZcashFoundation/reddsa/pull/22 was merged with a squash-commit, which caused the revision in the branch we were patching with to no longer exist.
=> Fix patch revision for `reddsa` crate

benches/note_decryption.rs
The benchmark assumed that the first action in the bundle was for the
recipient it had added, but we've started shuffling recipients within
actions, and the builder pads to a minimum of two actions. This meant
that 50% of benchmark runs would fail to start, but would proceed fine
if they did start (as the bundle is cached for the entire test).
We now add two recipients, to cancel out the effect of the padding and
shuffle.
=> Make note decryption benchmark reliable

Cargo.toml, src/note_encryption.rs
This adapts to API changes in https://github.com/zcash/librustzcash/pull/633 without changing the behaviour for Orchard.
=> Dummy implementation of Domain API change for prepared ivk and epk

Cargo.toml
zcash/orchard#357 pointed the patch at the PR branch's repository, which broke as soon as the PR branch was deleted from that repository.
=> Point patch directive at `zcash/librustzcash`

CHANGELOG.md, src/address.rs, src/keys.rs, src/note.rs, src/note_encryption.rs
One use-case is to enable wallets to store notes and diversifiers on disk.
=> Publicize necessary functionality for creating diversifiers and notes from data

CHANGELOG.md, src/circuit.rs
This supports downstream users that want more control over how proof batches are processed, instead of just batch validating Orchard bundles with `orchard::bundle::BatchValidator`.
=> Expose `Proof::add_to_batch` in public API

src/builder.rs
=> Correct the doc comment and add a test for `Builder::value_balance`

src/value.rs
This PR adds API for creating `ValueCommitment`s.
It enables us serialize less data when passing proof witness from HWW to a Prover.
=> Publicize `ValueCommitment::derive` constructor

CHANGELOG.md, src/builder.rs
The `Input/OutputView` traits are nearly straight-copied from https://github.com/zcash/librustzcash/blob/main/zcash_primitives/src/transaction/components/sapling/fees.rs, I'm assuming that interface is the desired one to this kind of functionality.
=> Add spends/outputs getter fns to builders for use in change calculation

.github/workflows/ci.yml, Cargo.toml
Update to make use of the floor-planner-v1-legacy-pdqsort feature.
=> Upgrade patch version of halo2 dependencies.

CHANGELOG.md, Cargo.toml, src/builder.rs, src/note_encryption.rs
This can be merged prior to a `zcash_note_encryption 0.3.0` release, though it will need to be updated to upgrade to such a release prior to `orchard 0.4.0`.
=> Migrate to zcash_note_encryption 0.3.0

src/spec.rs
=> Fix variable name in `spec::diversify_hash`

Cargo.toml, src/builder.rs, src/tree.rs, tests/builder.rs
This also removes the `bridgetree` transitive dependency when building using the `test-dependencies` feature flag, as the only use of it can be satisfied just with `incrementalmerkletree`.
=> Update the `incrementalmerkletree` and `bridgetree` patch versions.

src/note_encryption.rs
The consistency check between `esk` and `ephemeral_key` is checked inside `zcash_note_encryption::try_output_recovery_with_ock`, and the requirement to check it inside the `Domain` implementation is being lifted in zcash/librustzcash#848.
Removing the check here improves performance, both because we avoid an extra scalar multiplication from `esk.derive_public()`, and because we avoid an unnecessary `spec::diversify_hash()` call which is expensive for Orchard.
=> Remove redundant checks during note encryption

Cargo.toml, src/note_encryption.rs
Requires https://github.com/zcash/librustzcash/pull/851
=> Update `zcash_note_encryption` to remove unused arguments from `parse_note_plaintext_without_memo_ovk`

CHANGELOG.md, benches/circuit.rs, benches/note_decryption.rs, src/builder.rs, src/bundle.rs, src/tree.rs, src/value.rs, tests/builder.rs
An alternative/extension to #403
=> Add a public bundle-builder function as an alternative to the mutable builder.

CHANGELOG.md, benches/circuit.rs, benches/note_decryption.rs, src/builder.rs, tests/builder.rs
In order to be able to associate requested spends and outputs with the indices of the actions that execute these operations, it is necessary to track the randomization of inputs and outputs and return the mappings that resulted from that shuffling.
=> Return bundle metadata from bundle building.

Cargo.toml, src/constants/fixed_bases/commit_ivk_r.rs, src/constants/fixed_bases/note_commit_r.rs, src/constants/fixed_bases/nullifier_k.rs, src/constants/fixed_bases/spend_auth_g.rs, src/constants/fixed_bases/value_commit_r.rs, src/constants/fixed_bases/value_commit_v.rs
* Add a pointer to how the `Z` and `U` constants for fixed-base scalar multiplication can be reproduced.
* Correct errors and omissions in the documentation of the fixed-base generators.
=> Improve documentation for fixed-base constants

CHANGELOG.md, Cargo.lock, Cargo.toml, src/keys.rs
According to the [FROST book](https://frost.zfnd.org/zcash/technical-details.html) the ASK is split using FROST and its verifying key is the ak that should be used to generate the Orchard Full Viewing Key.
Allow SpendValidatingKey to be constructed from bytes
closes #427
As we agreed with @daira at Z|ECC, this adds a FROST feature flag so that public interface of the 
crate is not altered in its meaning for non-FROST applications.
Key derivation is intended to be done on a specific way for usual
applications. Interface changes introduce by FROST can pose a risk
for the rest of the use cases that don't involve the assumptions
of the FROST signature scheme protocol. we don't want non-FROST
cases to make use the helper functions FROST needs to derive the 
needed key elements.
There are other …
=> Allow SpendValidatingKey to be constructed from bytes

src/builder.rs, src/pczt.rs, src/pczt/parse.rs, src/pczt/updater.rs
This is necessary in order for Signers to display the address encoding that a user is expecting to confirm.
=> pczt: Add output field for storing the user-facing address

CHANGELOG.md, Cargo.lock, Cargo.toml, src/builder.rs, src/bundle.rs, src/bundle/batch.rs, src/circuit.rs, src/constants/fixed_bases.rs, src/keys.rs, src/lib.rs, src/note_encryption.rs, src/pczt.rs, src/pczt/io_finalizer.rs, src/pczt/parse.rs, src/pczt/prover.rs, src/pczt/updater.rs, src/primitives/redpallas.rs, src/spec.rs, src/test_vectors/keys.rs, src/test_vectors/merkle_path.rs, src/test_vectors/note_encryption.rs, src/tree.rs
This includes everything for `no-std` support except the `std` feature flag.
=> Keystone preparations

CHANGELOG.md, Cargo.lock, Cargo.toml, src/builder.rs, src/bundle.rs, src/keys.rs, src/lib.rs, src/primitives/redpallas.rs, src/spec.rs, src/value.rs
This cannot be merged until we have a `no_std` supporting `nonempty` release to depend upon.
=> Add no-std support via a default-enabled `std` feature flag

CHANGELOG.md, Cargo.lock, Cargo.toml, src/pczt.rs, src/tree.rs, tests/builder.rs
This also requires us to replace the use of `bridgetree` in tests with `shardtree`.
=> Upgrade `incrementalmerkletree` to version 0.8.1

CHANGELOG.md, Cargo.lock, Cargo.toml, src/zip32.rs
Blocks on https://github.com/zcash/zcash_spec/pull/7 and https://github.com/zcash/zip32/pull/24.
=> Migrate to `zcash_spec 0.2.1` and `zip32 0.2.0`

CHANGELOG.md, benches/circuit.rs, benches/note_decryption.rs, src/builder.rs, src/pczt.rs, tests/builder.rs
This is a standard convention for Zcash memos, but it doesn't have any relevance to the general Orchard protocol and as such doesn't belong in this crate.
=> Remove 0xf6 empty memo convention.

.github/workflows/ci.yml, .github/workflows/lints-stable.yml, Cargo.toml, README.md
* Document needing the `no_std` feature of `typenum` for no_std builds.
* CI: Fixes to `build-nodefault` (renamed to `build-nostd`).
* CI: Add a clippy lint for no_std on `wasm32-wasi`.
* Depend on `halo2_gadgets` with default-features = false.
This fixes the CI steps for `no_std` builds.
=> CI and dependency fixes for `no_std`
