- .github/workflows/book.yml
- .github/workflows/ci.yml
https://blog.rust-lang.org/2021/01/04/mdbook-security-advisory.html
> Use mdbook 0.4.5

- book/src/design/commitments.md
- book/src/design/nullifiers.md
* Swap ak and nk in the input to ShortCommit<sup>ivk</sup>. They somehow got reversed relative to Sapling.
* Explain in more detail the argument for Balance.
* F might be Poseidon.
* Make some formatting changes so that it's correct Markdown.
> Nullifier rationale

- book/src/design.md
- book/src/design/commitments.md
- book/src/design/nullifiers.md
This reverts to the previous nullifier design (which we've determined is actually fine).
> book: Add nullifier rationale

- src/bundle.rs
This enables us to construct Bundles at various stages of
authorization:
- `Bundle<Unauthorized>`: A bundle with all effecting data but no
proofs or signatures.
- `Bundle<Authorized>`: A bundle with all proofs and signatures,
suitable for inclusion in a block.
- `Bundle<Partial>`: Example of some in-progress bundle authorization,
for example during a FROST threshold multisignature protocol.
Also adds the bundle flags field from ZIP 225.
> Make Bundle a parametric type over an Authorization trait

- Cargo.toml
- src/keys.rs
- src/primitives/sinsemilla.rs
- src/spec.rs
This brings us current with the `halo2` crate (and also moves us to pinning its revision).
> Use the pasta_curves crate directly

- src/primitives.rs
- src/primitives/sinsemilla.rs
- src/primitives/sinsemilla/constants.rs
- src/spec.rs
Please review with whitespace changes hidden.
> Generalise Sinsemilla API

- src/address.rs
- src/keys.rs
- src/note.rs
- src/note/commitment.rs
- src/note/nullifier.rs
- src/spec.rs
- src/value.rs
> Note structure

- book/src/design/keys.md
> [Book] Explain the decision to exclude zero points and scalars for KA.Orchard

- Cargo.toml
- src/bundle.rs
- src/keys.rs
- src/note.rs
- src/note/commitment.rs
- src/primitives/sinsemilla.rs
- src/primitives/sinsemilla/addition.rs
- src/spec.rs
This brings in the type changes from the spec, that were made to address feedback in the NCC interim report. It also fixes a type error in `bundle::Action`.
> Note commitment updates

- book/src/design/nullifiers.md
> [Book] Update nullifier explanation to include Extract_P

- Cargo.toml
- src/circuit/gadget/ecc.rs
- src/circuit/gadget/ecc/chip.rs
- src/circuit/gadget/ecc/chip/add.rs
- src/circuit/gadget/ecc/chip/add_complete.rs
- src/circuit/gadget/ecc/chip/double.rs
- src/circuit/gadget/ecc/chip/mul.rs
- src/circuit/gadget/ecc/chip/mul_fixed.rs
- src/circuit/gadget/ecc/chip/mul_fixed_short.rs
- src/circuit/gadget/ecc/chip/util.rs
- src/circuit/gadget/ecc/chip/witness_point.rs
- src/circuit/gadget/ecc/chip/witness_scalar_fixed.rs
- src/circuit/gadget/ecc/chip/witness_scalar_fixed_short.rs
- src/circuit/gadget/ecc/chip/witness_scalar_var.rs
- src/constants.rs
Fixed #23 to work with https://github.com/zcash/halo2/pull/253.
> [WIP] Fix ECC implementation to work with new Chip trait

- src/circuit.rs
- src/keys.rs
- src/note.rs
- src/note/nullifier.rs
- src/primitives/redpallas.rs
The circuit is just a single gate to ensure that the prover has polynomials to run on.
> Proving and verifying keys, and placeholder proof logic

- .github/workflows/ci.yml
- Cargo.toml
- src/builder.rs
- src/bundle.rs
- src/keys.rs
- src/lib.rs
- src/note.rs
- src/note/commitment.rs
- src/primitives/redpallas.rs
- src/tree.rs
- src/value.rs
This is a modular bundle builder, the pieces of which can be used within a top-level transaction builder.
> Bundle builder

- src/bundle.rs
- src/circuit.rs
- src/note.rs
- src/primitives/redpallas.rs
This is required for proptest generation that handles shrinking
correctly in librustzcash.
> Make the `Bundle` type implement `Clone`

- Cargo.toml
- src/circuit/gadget/ecc.rs
> Modify ECC gadget to work with chip refactor

- src/circuit/gadget.rs
- src/circuit/gadget/utilities.rs
- src/circuit/gadget/utilities/cond_swap.rs
- src/circuit/gadget/utilities/enable_flag.rs
- src/circuit/gadget/utilities/plonk.rs
> Chip for general utils

- Cargo.toml
- src/circuit/gadget/poseidon/pow5t3.rs
- src/circuit/gadget/utilities/cond_swap.rs
- src/circuit/gadget/utilities/enable_flag.rs
This brings in:
- Fixes and improvements to `MockProver`.
- Support for annotating constraints within gates.
- Removal of Selector rotations.
> Migrate to latest version of halo2

- book/src/design/commitment-tree.md
cf. https://zips.z.cash/protocol/protocol.pdf#thmuncommittedorchard
> [book] commitment-tree.md: Update Uncommitted^Orchard from 0 -> 2.

- Cargo.toml
- src/circuit/gadget/ecc.rs
- src/circuit/gadget/ecc/chip.rs
- src/circuit/gadget/ecc/chip/add.rs
- src/circuit/gadget/ecc/chip/add_incomplete.rs
- src/circuit/gadget/ecc/chip/witness_point.rs
The variable- and fixed-base scalar multiplication instructions are implemented in #111.
> [ECC chip] Incomplete and complete addition

- src/constants.rs
- src/value.rs
> Use constants for value commitment hash-to-curve.

- src/tree.rs
See https://github.com/zcash/zips/pull/530
> Implements the updated, total definition of MerkleCRH^Orchard

- book/src/design/circuit/gadgets/ecc/addition.md
- book/src/design/circuit/gadgets/ecc/var-base-scalar-mul.md
Also includes some formatting improvements.
> [book] Fixes to the completeness arguments for cases of complete addition, and a fix to the last step of variable-base scalar multiplication

- book/src/design/circuit/gadgets/sinsemilla/note-commit.md
> book: Fixes to NoteCommit page

- src/circuit/gadget/utilities/lookup_range_check.rs
This PR is based on #101 and documented in #162.
The lookup running sum decomposition uses the same lookup table as its short variant. These two lookup arguments have been merged.
Co-authored-by: Daira Hopwood <daira@jacaranda.org>
Co-authored-by: Jack Grigg <jack@electriccoin.co>
> Merge lookup arguments in `lookup_range_check` helper.

- book/src/design/circuit/gadgets/decomposition.md
This documents the change implemented in #161.
> [book] Merge lookup arguments for normal and short variants

- Cargo.toml
- src/circuit.rs
- src/circuit/gadget/ecc.rs
- src/circuit/gadget/ecc/chip/mul_fixed/short.rs
- src/circuit/gadget/sinsemilla.rs
- src/circuit/gadget/sinsemilla/chip.rs
- src/circuit/gadget/sinsemilla/chip/generator_table.rs
- src/circuit/gadget/sinsemilla/commit_ivk.rs
- src/circuit/gadget/sinsemilla/merkle.rs
- src/circuit/gadget/sinsemilla/note_commit.rs
- src/circuit/gadget/utilities/lookup_range_check.rs
> Update to assign_table API.

- Cargo.toml
- benches/primitives.rs
- src/primitives.rs
- src/primitives/poseidon.rs
- src/primitives/sinsemilla.rs
This PR also exposes these primitives in the public crate API.
> Add benchmarks for Poseidon and Sinsemilla primitives

- src/builder.rs
- src/keys.rs
- src/lib.rs
- src/spec/prf_expand.rs
- src/zip32.rs
Closes #30 
Needs test vectors from https://github.com/zcash-hackworks/zcash-test-vectors/issues/41.
> ZIP32 key derivation

- book/src/design/circuit/gadgets/sinsemilla.md
Co-authored-by: Jack Grigg <jack@electriccoin.co>
> [book] sinsemilla.md: Correct constraint degrees.

- book/src/design/circuit/gadgets/sinsemilla/note-commit.md
Documents changes made in #169.
> [book] Document NoteCommit region optimisations

- book/src/design/circuit/gadgets/sinsemilla/commit-ivk.md
Matches the change made in zcash/orchard#169.
> book: Update rotations for Commit^ivk region

- src/builder.rs
- src/circuit.rs
- src/circuit/gadget/sinsemilla/merkle.rs
- src/constants/util.rs
- src/tree.rs
> Tidy Merkle path logic.

- src/circuit.rs
- src/circuit/gadget/ecc.rs
- src/circuit/gadget/ecc/chip.rs
- src/circuit/gadget/ecc/chip/add.rs
- src/circuit/gadget/ecc/chip/add_incomplete.rs
- src/circuit/gadget/ecc/chip/mul.rs
- src/circuit/gadget/ecc/chip/mul/incomplete.rs
- src/circuit/gadget/ecc/chip/mul_fixed.rs
- src/circuit/gadget/ecc/chip/mul_fixed/base_field_elem.rs
- src/circuit/gadget/ecc/chip/mul_fixed/full_width.rs
- src/circuit/gadget/ecc/chip/mul_fixed/short.rs
- src/circuit/gadget/ecc/chip/witness_point.rs
- src/circuit/gadget/sinsemilla.rs
- src/circuit/gadget/sinsemilla/chip.rs
- src/circuit/gadget/sinsemilla/chip/hash_to_point.rs
- src/circuit/gadget/sinsemilla/merkle/chip.rs
- src/circuit/gadget/sinsemilla/note_commit.rs
- src/circuit_description
- src/primitives/sinsemilla.rs
- src/primitives/sinsemilla/addition.rs
- Several witnessed points are now constrained to be non-identity points.
- SinsemillaCommit now uses complete addition for the blinding factor.
> Circuit bugfixes

- Cargo.toml
> Use reddsa 0.1 instead of the git dependency

- src/circuit.rs
- src/circuit/gadget.rs
- src/circuit/gadget/poseidon.rs
- src/circuit/gadget/poseidon/pow5.rs
- src/circuit_description
> Generalise Poseidon gadget over `WIDTH`, `RATE`

- src/keys.rs
Needed for https://github.com/zcash/zcash/pull/5357
> Add construction of DiversifierIndex directly from bytes.

- book/macros.txt
- book/src/design/circuit/gadgets/decomposition.md
- book/src/design/circuit/gadgets/ecc/fixed-base-scalar-mul.md
- book/src/design/circuit/gadgets/ecc/var-base-scalar-mul.md
- src/circuit/gadget/ecc/chip/mul.rs
- src/circuit/gadget/ecc/chip/mul/complete.rs
- src/circuit/gadget/ecc/chip/mul/incomplete.rs
- src/circuit/gadget/ecc/chip/mul_fixed/short.rs
- src/circuit/gadget/utilities.rs
- src/circuit/gadget/utilities/cond_swap.rs
- src/circuit_description
Closes https://github.com/zcash/orchard/issues/143.
> circuit: Use `N - x` instead of `x - N`.

- src/circuit/gadget/ecc/chip/mul.rs
- src/circuit/gadget/ecc/chip/mul/complete.rs
- src/circuit/gadget/utilities.rs
- src/circuit/gadget/utilities/cond_swap.rs
- src/circuit_description
> circuit: Introduce ternary expression helper.

- benches/poseidon.rs
- benches/primitives.rs
- src/circuit.rs
- src/circuit/gadget/poseidon.rs
- src/circuit/gadget/poseidon/pow5.rs
- src/primitives/poseidon.rs
- src/primitives/poseidon/p128pow5t3.rs
- src/spec.rs
> Rewrite Poseidon implementation

- .github/workflows/bench.yml
- benches/circuit.rs
> CI: Benchmark tweaks

- src/keys.rs
`ak_P` is not allowed to be the identity in the Orchard protocol. We
were enforcing this by construction in most places, except for the
parsing of an Orchard full viewing key.
Closes zcash/orchard#261.
> Reject the identity in `SpendValidatingKey::from_bytes`

- src/keys.rs
- src/spec.rs
> spec.rs: Check that commit_ivk returns a nonzero base.

- CHANGELOG.md
- benches/circuit.rs
- benches/note_decryption.rs
- benches/small.rs
- src/address.rs
- src/builder.rs
- src/circuit.rs
- src/keys.rs
- src/note.rs
- tests/builder.rs
Closes #303. Closes #304.  
Co-authored-by: Jack Grigg <jack@electriccoin.co>
Co-authored-by: Daira Hopwood <daira@jacaranda.org>
> Add explicit scoping for viewing keys and addresses

- CHANGELOG.md
- Cargo.toml
> Release 0.1.0-beta.3

- Cargo.toml
- benches/note_decryption.rs
- src/address.rs
- src/builder.rs
- src/bundle.rs
- src/circuit.rs
- src/circuit/commit_ivk.rs
- src/circuit/note_commit.rs
- src/constants/load.rs
- src/keys.rs
- src/note/nullifier.rs
- src/note_encryption.rs
- src/primitives/redpallas.rs
- src/spec.rs
- src/tree.rs
- src/value.rs
- src/zip32.rs
- tests/builder.rs
> Cleanups for MSRV 1.56.1

- Cargo.toml
- src/circuit.rs
- src/circuit/commit_ivk.rs
- src/circuit/note_commit.rs
Best reviewed with whitespace hidden.
> Migrate to `halo2::plonk::Constraints` helper

- CHANGELOG.md
- src/action.rs
- src/builder.rs
- src/bundle.rs
- src/bundle/commitments.rs
- src/circuit.rs
- src/circuit/commit_ivk.rs
- src/circuit/note_commit.rs
- src/constants/sinsemilla.rs
- src/keys.rs
- src/lib.rs
- src/note.rs
- src/note/commitment.rs
- src/note_encryption.rs
- src/primitives/redpallas.rs
- src/spec.rs
- src/tree.rs
- src/value.rs
- src/zip32.rs
> Preparations for `no-std` support

- src/builder.rs
> Update `Builder::build` docs

- CHANGELOG.md
- Cargo.toml
- book/src/design/actions.md
- src/action.rs
- src/builder.rs
- src/bundle.rs
- src/circuit.rs
- src/circuit/commit_ivk.rs
- src/circuit/gadget.rs
- src/circuit/gadget/add_chip.rs
- src/circuit/note_commit.rs
- src/tree.rs
- src/value.rs
> Changes from circuit review

- src/builder.rs
> Support externally computed signatures

- Cargo.toml
- src/circuit.rs
- src/constants/fixed_bases.rs
Use https://github.com/zcash/halo2/pull/522.
> Use new halo2 `FixedPoint` API.

- Cargo.toml
- src/circuit.rs
- src/circuit/commit_ivk.rs
- src/circuit/gadget.rs
- src/circuit/note_commit.rs
- src/constants/fixed_bases/commit_ivk_r.rs
- src/constants/fixed_bases/note_commit_r.rs
- src/constants/sinsemilla.rs
- src/note/commitment.rs
- src/spec.rs
- src/tree.rs
Includes API changes made in zcash/halo2#573.
> Migrate to final `halo2_gadgets` pre-release revision

- COPYING
Update COPYING file with BOSL exception text.
> Add exception text

- book/src/IDENTIFIERS.json
- book/src/design/circuit/commit-ivk.md
- book/src/design/circuit/note-commit.md
- src/circuit.rs
- src/circuit/commit_ivk.rs
- src/circuit/note_commit.rs
> Add protocol rule links for the Orchard circuit constraints

- LICENSE-BOSL
> Change copyright attribution for the LICENSE-BOSL file

- src/note_encryption.rs
> Add OrchardDomain::for_nullifier and CompactAction::from_parts

- Cargo.toml
> Upgrade `incrementalmerkletree` dependency to version 0.3.1

- Cargo.toml
> Migrate to `fpe 0.6`

- book/src/design/circuit/note-commit.md
> [book] Add a missing right parenthesis

- src/action.rs
This was originally written when the Orchard design had not yet been finalized.
> Trivial update to the doc for `struct Action` 
